package com.example.summit;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents an item with a summary, name, and date, stored in a Room database.
 */
@Entity
public class Item {
    /**
     * The unique identifier for the item. This field is automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    /**
     * The main text content of the summary.
     */
    private String summaryText; // actual summary
    /**
     * A name or title for the summary.
     */
    private String summaryName;
    /**
     * The date associated with the summary.
     */
    private String summaryDate;

    /**
     * Constructs a new Item object.
     *
     * @param summaryText The main text content of the summary.
     * @param summaryName A name or title for the summary.
     * @param summaryDate The date associated with the summary.
     */
    public Item(String summaryText, String summaryName, String summaryDate) {
        this.summaryText = summaryText;
        this.summaryName = summaryName;
        this.summaryDate = summaryDate;
    }

    /**
     * Gets the unique identifier of the item.
     *
     * @return The item's ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the item.
     *
     * @param id The new ID for the item.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the main text content of the summary.
     *
     * @return The summary text.
     */
    public String getSummaryText() {
        return summaryText;
    }

    /**
     * Sets the main text content of the summary.
     *
     * @param summaryText The new summary text.
     */
    public void setSummaryText(String summaryText) {
        this.summaryText = summaryText;
    }

    /**
     * Gets the name or title of the summary.
     *
     * @return The summary name.
     */
    public String getSummaryName() {
        return summaryName;
    }

    /**
     * Sets the name or title of the summary.
     *
     * @param summaryName The new summary name.
     */
    public void setSummaryName(String summaryName) {
        this.summaryName = summaryName;
    }

    /**
     * Gets the date associated with the summary.
     *
     * @return The summary date.
     */
    public String getSummaryDate() {
        return summaryDate;
    }

    /**
     * Sets the date associated with the summary.
     *
     * @param summaryDate The new summary date.
     */
    public void setSummaryDate(String summaryDate) {
        this.summaryDate = summaryDate;
    }
}